"""
test_ocr_pipeline_hardening.py

P0/P1 Production Hardening Tests — Audit Phase
Tests: file size limit, corrupt image, empty file, retryable classification,
       structured error contract, typed OCRPipelineMetrics, request_id traceability.
"""
import io
import os
import uuid

import pytest
from fastapi.testclient import TestClient

os.environ.setdefault("MEDISCAN_TEST_MODE", "true")

from app.schemas.ocr_schema import OCRPipelineMetrics


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _make_minimal_png_bytes() -> bytes:
    """Tạo file PNG 1x1 pixel hợp lệ (đã verify qua PIL.load()) để test upload."""
    import base64
    # 1x1 red pixel PNG generated by PIL — verified to pass PIL.load() check
    b64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC"
    return base64.b64decode(b64)


def _make_corrupt_bytes() -> bytes:
    return b"\xff\xd8\xff\xe0" + b"\x00" * 20


def _auth_headers(client) -> dict:
    unique = uuid.uuid4().hex[:8]
    resp = client.post("/api/v1/auth/register", json={
        "email": f"harden_{unique}@mediscan.ai",
        "username": f"harden_{unique}",
        "password": "Harden@1234",
        "full_name": "Harden Test",
    })
    assert resp.status_code == 201, f"Register failed: {resp.text}"
    token = resp.json()["accessToken"]
    return {"Authorization": f"Bearer {token}"}


# ─────────────────────────────────────────────────────────────────────────────
# Schema Unit Tests
# ─────────────────────────────────────────────────────────────────────────────

class TestOCRPipelineMetricsSchema:
    def test_default_values_are_zero(self):
        m = OCRPipelineMetrics()
        assert m.preprocessor_ms == 0
        assert m.ocr_inference_ms == 0
        assert m.total_latency_ms == 0

    def test_all_fields_set(self):
        m = OCRPipelineMetrics(preprocessor_ms=10, ocr_inference_ms=200, total_latency_ms=210)
        assert m.preprocessor_ms == 10

    def test_negative_rejected(self):
        import pydantic
        with pytest.raises(pydantic.ValidationError):
            OCRPipelineMetrics(preprocessor_ms=-1)

    def test_camel_alias(self):
        m = OCRPipelineMetrics(preprocessor_ms=5, ocr_inference_ms=100, total_latency_ms=105)
        d = m.model_dump(by_alias=True)
        assert "preprocessorMs" in d
        assert "ocrInferenceMs" in d


class TestFullScanResponseHasRequestId:
    def test_schema_has_request_id_field(self):
        from app.schemas.ocr_schema import FullScanResponse
        fields = FullScanResponse.model_fields
        assert "request_id" in fields
        assert fields["request_id"].default == ""


# ─────────────────────────────────────────────────────────────────────────────
# HTTP Integration Tests
# ─────────────────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def client():
    from app.main import app
    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="module")
def auth_headers(client):
    return _auth_headers(client)


class TestOCRUploadValidation:
    def test_no_auth_returns_401(self, client):
        png = _make_minimal_png_bytes()
        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("test.png", png, "image/png")},
            data={"source_type": "packaging"},
        )
        assert resp.status_code == 401

    def test_invalid_mime_type_returns_400(self, client, auth_headers):
        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("doc.pdf", b"%PDF-1.4", "application/pdf")},
            data={"source_type": "packaging"},
            headers=auth_headers,
        )
        assert resp.status_code == 400
        body = resp.json()
        assert body["detail"]["error_code"] == "INVALID_MIME_TYPE"
        assert body["detail"]["retryable"] is False

    def test_invalid_extension_returns_400(self, client, auth_headers):
        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("scan.tiff", _make_minimal_png_bytes(), "image/tiff")},
            data={"source_type": "prescription"},
            headers=auth_headers,
        )
        assert resp.status_code == 400
        body = resp.json()
        assert body["detail"]["error_code"] == "INVALID_EXTENSION"
        assert body["detail"]["retryable"] is False

    def test_invalid_source_type_returns_400(self, client, auth_headers):
        png = _make_minimal_png_bytes()
        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("test.png", png, "image/png")},
            data={"source_type": "unknown_pipeline"},
            headers=auth_headers,
        )
        assert resp.status_code == 400
        body = resp.json()
        assert body["detail"]["error_code"] == "INVALID_SOURCE_TYPE"
        assert body["detail"]["retryable"] is False

    def test_empty_file_returns_400(self, client, auth_headers):
        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("empty.png", b"", "image/png")},
            data={"source_type": "packaging"},
            headers=auth_headers,
        )
        assert resp.status_code == 400
        body = resp.json()
        assert body["detail"]["error_code"] == "EMPTY_FILE"
        assert body["detail"]["retryable"] is False

    def test_corrupt_image_returns_400(self, client, auth_headers):
        corrupt = _make_corrupt_bytes()
        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("corrupt.jpg", corrupt, "image/jpeg")},
            data={"source_type": "packaging"},
            headers=auth_headers,
        )
        assert resp.status_code == 400
        body = resp.json()
        assert body["detail"]["error_code"] == "CORRUPT_IMAGE"
        assert body["detail"]["retryable"] is False


class TestRetryableClassification:
    def test_name_error_not_retryable(self, client, auth_headers, monkeypatch):
        from app.services import ocr_engine as ocr_module

        def _raise(*_args, **_kwargs):
            raise NameError("name 'SomeMissing' is not defined")

        monkeypatch.setattr(ocr_module.ocr_engine, "extract_packaging_label", _raise)

        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("test.png", _make_minimal_png_bytes(), "image/png")},
            data={"source_type": "packaging"},
            headers=auth_headers,
        )
        assert resp.status_code == 500
        assert resp.json()["detail"]["retryable"] is False

    def test_connection_error_retryable(self, client, auth_headers, monkeypatch):
        from app.services import ocr_engine as ocr_module
        import httpx

        def _raise(*_args, **_kwargs):
            raise httpx.ConnectError("Cannot connect")

        monkeypatch.setattr(ocr_module.ocr_engine, "extract_packaging_label", _raise)

        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("test.png", _make_minimal_png_bytes(), "image/png")},
            data={"source_type": "packaging"},
            headers=auth_headers,
        )
        assert resp.status_code == 500
        assert resp.json()["detail"]["retryable"] is True

    def test_500_has_request_id_in_detail(self, client, auth_headers, monkeypatch):
        from app.services import ocr_engine as ocr_module

        def _raise(*_args, **_kwargs):
            raise RuntimeError("Simulated crash")

        monkeypatch.setattr(ocr_module.ocr_engine, "extract_packaging_label", _raise)

        resp = client.post(
            "/api/v1/ocr/scan",
            files={"file": ("test.png", _make_minimal_png_bytes(), "image/png")},
            data={"source_type": "packaging"},
            headers=auth_headers,
        )
        assert resp.status_code == 500
        detail = resp.json()["detail"]
        assert "request_id" in detail
        assert len(detail["request_id"]) > 0
        assert "Simulated crash" not in detail.get("message", "")
